spring:
  application:
    name: qiyiProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19991204
    url: jdbc:mysql://localhost:3306/atcrowdfunding?useSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.188.146
    port: 6379
server:
  port: 8000
mybatis:
  mapper-locations: classpath:com/offcn/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com:
      offcn: debug
  file:
    path: D:\Users\LJT\Documents\IdeaProjects\offcn-parent\log\
oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  bucketDomain: qiyi11.oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5tP1WGQA3qseMDBssmAy
  accessKeySecret: wdFO1COgwLXX6VNC4QXoevBFPAAFiH
  bucketName: qiyi11